"""
Django settings for Blog project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-knm-3a33xrc@#7&aj1p5t^q(s@4vq$ds=uh*hya!6spn5crsf_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 我的应用
    'blogs',
    # 第三方库
    'django_bootstrap5',
    # 用户
    'users',
    # markdown支持
    'markdownify',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'  # 修改为中文

TIME_ZONE = 'Asia/Shanghai'  # 修改为本地时区

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# 允许更多标签（比如图片）
MARKDOWNIFY = {
    "default": {
        "BLEACH": True,

        # 1. 扩展插件：确保 pymdownx.tilde 被加载
        "MARKDOWN_EXTENSIONS": [
            'markdown.extensions.extra',  # 基础包
            'markdown.extensions.nl2br',  # 换行
            'pymdownx.tilde',  # 修复删除线 (~~)
            'pymdownx.tasklist',  # 任务列表
        ],

        # 2. 标签白名单：必须包含 del (删除线) 和 hr (分割线)
        "WHITELIST_TAGS": [
            'a', 'abbr', 'b', 'blockquote', 'code', 'em', 'i', 'li', 'ol', 'p', 'strong', 'ul',
            'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
            'pre', 'br', 'hr', 'img',
            'sub', 'sup', 'del',  # <--- 关键：允许 del 标签
            'table', 'thead', 'tbody', 'th', 'tr', 'td',
            'input', 'span', 'div'
        ],

        "WHITELIST_ATTRS": {
            '*': ['class', 'style'],
            'a': ['href', 'title', 'target'],
            'img': ['src', 'alt', 'title', 'width', 'height'],
            'input': ['type', 'checked', 'disabled'],
        },

        "WHITELIST_STYLES": [
            'color', 'font-weight', 'background-color', 'width', 'height',
            'text-align', 'border'
        ],
        "MARKDOWN_EXTENSION_CONFIGS": {
            "pymdownx.tilde": {
                "subscript": False,  # ✅ 只关这个
            },
            "pymdownx.tasklist": {
                "custom_checkbox": True,
            },
        },

        "STRIP": False,
    }
}

# 未登录用户的重定向地址
LOGIN_URL = 'users:login'
# 登录成功去主页
LOGIN_REDIRECT_URL = 'blogs:index'
# 注销成功去主页
LOGOUT_REDIRECT_URL = 'blogs:index'